swagger: "2.0"
info:
  version: "1.0"
  title: Hello world endpoint
  description: A simple hello world endpoint

paths:
  /hello-world:
    get:
      summary: Get user chats
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${helloWorldLambdaArn}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # Replace '*' with your actual allowed origin
        httpMethod: "POST"
        type: "aws_proxy"
      responses:
        200:
          description: "Successful response"
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: "'*'"
            Access-Control-Allow-Methods:
              type: string
              default: "'GET,POST,OPTIONS'"
            Access-Control-Allow-Headers:
              type: string
              default: "'Content-Type'"
    options:
      summary: CORS support
      description: Send a preflight request to check for CORS
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: CORS response
          headers:
            Access-Control-Allow-Origin:
              type: string
              default: "'*'" # Ideally, replace '*' with your specific allowed origins
            Access-Control-Allow-Methods:
              type: string
              default: "'GET,POST,PUT,PATCH,OPTIONS,DELETE'"
            Access-Control-Allow-Headers:
              type: string
              default: "'Content-Type'"
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'" # Same here for specific origins
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,PATCH,OPTIONS,DELETE'"
            responseTemplates:
              application/json: ""
